### ISSUE TITLE
Support addition of custom (docType) attribute(s) when importing data

### ISSUE THREAD

**Issue by blbryant** [couchbaselabs/cbsh-gsi#1]
cbimport does not support this.  But it would be useful to help insert useful field(s) into the data as we are importing.

**Comment by ingenthr** [comment]
just to check, I think you mean add a "type": "user" attribute, correct?  That's [already do-able with nu builtins](https://www.nushell.sh/commands/insert.html).

**Comment by ingenthr** [comment]
Though, now that I think of it, we may need to coerce it into the content section.

**Comment by ingenthr** [comment]
by the way, you posted this on the wrong project, something I have already emailed @prataprc about.  The issue to track on this is probably:
https://github.com/couchbaselabs/couchbase-shell/issues/16 

Or please add the use case to https://github.com/couchbaselabs/couchbase-shell
